a = int(input("Enter first number(a): "))
b = int(input("Enter first number(b): "))
print("Addition:")
print(a + b)
print("Subtraction:")
print(a - b)
print("Multiplication:")
print(a * b)
print("Division:")
print(a / b)